# Generated by Django 3.1.1 on 2020-09-30 15:24

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='roomname',
            new_name='name',
        ),
        migrations.AddField(
            model_name='room',
            name='group_name',
            field=models.SlugField(default=django.utils.timezone.now, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='room',
            name='round',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='room',
            name='state',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='user',
            name='nickname',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='ready_state',
            field=models.IntegerField(default=0),
        ),
    ]
